//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQueenalya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instansi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instansi()
        {
            this.Gurus = new HashSet<Guru>();
            this.Siswas = new HashSet<Siswa>();
        }
    
        public long id { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public byte[] foto_instansi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guru> Gurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siswa> Siswas { get; set; }
    }
}
