//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQueenalya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PKLEntities : DbContext
    {
        public PKLEntities()
            : base("name=PKLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absen> Absens { get; set; }
        public virtual DbSet<Guru> Gurus { get; set; }
        public virtual DbSet<Instansi> Instansis { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Siswa> Siswas { get; set; }
    }
}
