//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQueenalya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siswa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siswa()
        {
            this.Absens = new HashSet<Absen>();
        }
    
        public long id { get; set; }
        public long nis { get; set; }
        public string nama { get; set; }
        public string kelas { get; set; }
        public string alamat { get; set; }
        public long no_hp { get; set; }
        public string instansi_nama { get; set; }
        public byte[] foto_siswa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absen> Absens { get; set; }
        public virtual Instansi Instansi { get; set; }
    }
}
